import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import "dotenv/config";
import { pool, query } from "../src/config/db.js";

function normalizeIngredients(value) {
    if (Array.isArray(value)) {
        return value
            .filter((item) => typeof item === "string")
            .map((item) => item.trim())
            .filter(Boolean);
    }

    if (typeof value === "string") {
        return value
            .split(",")
            .map((item) => item.trim())
            .filter(Boolean);
    }

    return [];
}

function formatValue(value, level = 0) {
    const pad = "  ".repeat(level);
    const nextPad = "  ".repeat(level + 1);

    if (value instanceof Date) {
        return `new Date(${JSON.stringify(value.toISOString())})`;
    }

    if (Array.isArray(value)) {
        if (value.length === 0) return "[]";
        const items = value.map((item) => `${nextPad}${formatValue(item, level + 1)}`);
        return `[
${items.join(",\n")}
${pad}]`;
    }

    if (value && typeof value === "object") {
        const entries = Object.entries(value).map(
            ([key, val]) => `${nextPad}${key}: ${formatValue(val, level + 1)}`
        );
        if (entries.length === 0) return "{}";
        return `{
${entries.join(",\n")}
${pad}}`;
    }

    return JSON.stringify(value);
}

async function main() {
    console.log("📦 Exporting current database to prisma/seed.data.js ...");

    const seedData = {
        users: await query("SELECT * FROM users"),
        refreshTokens: await query("SELECT * FROM refresh_tokens"),
        addresses: await query("SELECT * FROM addresses"),
        categories: await query("SELECT * FROM categories"),
        menuItems: (await query("SELECT * FROM menu_items")).map((item) => ({
            ...item,
            ingredients: normalizeIngredients(typeof item.ingredients === "string" ? JSON.parse(item.ingredients) : item.ingredients),
        })),
        coupons: await query("SELECT * FROM coupons"),
        subscriptionPlans: await query("SELECT * FROM subscription_plans"),
        subscriptions: await query("SELECT * FROM subscriptions"),
        orders: await query("SELECT * FROM orders"),
        orderItems: await query("SELECT * FROM order_items"),
        payments: await query("SELECT * FROM payments"),
        contactSubmissions: await query("SELECT * FROM contact_submissions"),
        blogPosts: await query("SELECT * FROM blog_posts"),
        siteSettings: await query("SELECT * FROM site_settings"),
    };

    const seedMeta = {
        exportedAt: new Date(),
    };

    const contents = `// Auto-generated by prisma/export-seed.js
// Do not edit manually.

export const seedMeta = ${formatValue(seedMeta)};

export const seedData = ${formatValue(seedData)};
`;

    const here = dirname(fileURLToPath(import.meta.url));
    const outputPath = join(here, "seed.data.js");

    await writeFile(outputPath, contents, "utf8");

    console.log("✅ Seed snapshot written:", outputPath);
}

main()
    .catch((error) => {
        console.error("❌ Export failed:", error);
        process.exit(1);
    })
    .finally(async () => {
        await pool.end();
    });
