import { PrismaClient } from "@prisma/client";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import "dotenv/config";

const prisma = new PrismaClient();

function normalizeIngredients(value) {
    if (Array.isArray(value)) {
        return value
            .filter((item) => typeof item === "string")
            .map((item) => item.trim())
            .filter(Boolean);
    }

    if (typeof value === "string") {
        return value
            .split(",")
            .map((item) => item.trim())
            .filter(Boolean);
    }

    return [];
}

function formatValue(value, level = 0) {
    const pad = "  ".repeat(level);
    const nextPad = "  ".repeat(level + 1);

    if (value instanceof Date) {
        return `new Date(${JSON.stringify(value.toISOString())})`;
    }

    if (Array.isArray(value)) {
        if (value.length === 0) return "[]";
        const items = value.map((item) => `${nextPad}${formatValue(item, level + 1)}`);
        return `[
${items.join(",\n")}
${pad}]`;
    }

    if (value && typeof value === "object") {
        const entries = Object.entries(value).map(
            ([key, val]) => `${nextPad}${key}: ${formatValue(val, level + 1)}`
        );
        if (entries.length === 0) return "{}";
        return `{
${entries.join(",\n")}
${pad}}`;
    }

    return JSON.stringify(value);
}

async function main() {
    console.log("📦 Exporting current database to prisma/seed.data.js ...");

    const seedData = {
        users: await prisma.user.findMany(),
        refreshTokens: await prisma.refreshToken.findMany(),
        addresses: await prisma.address.findMany(),
        categories: await prisma.category.findMany(),
        menuItems: (await prisma.menuItem.findMany()).map((item) => ({
            ...item,
            ingredients: normalizeIngredients(item.ingredients),
        })),
        coupons: await prisma.coupon.findMany(),
        subscriptionPlans: await prisma.subscriptionPlan.findMany(),
        subscriptions: await prisma.subscription.findMany(),
        orders: await prisma.order.findMany(),
        orderItems: await prisma.orderItem.findMany(),
        payments: await prisma.payment.findMany(),
        contactSubmissions: await prisma.contactSubmission.findMany(),
        blogPosts: await prisma.blogPost.findMany(),
        siteSettings: await prisma.siteSetting.findMany(),
    };

    const seedMeta = {
        exportedAt: new Date(),
    };

    const contents = `// Auto-generated by prisma/export-seed.js
// Do not edit manually.

export const seedMeta = ${formatValue(seedMeta)};

export const seedData = ${formatValue(seedData)};
`;

    const here = dirname(fileURLToPath(import.meta.url));
    const outputPath = join(here, "seed.data.js");

    await writeFile(outputPath, contents, "utf8");

    console.log("✅ Seed snapshot written:", outputPath);
}

main()
    .catch((error) => {
        console.error("❌ Export failed:", error);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
